package com.example.myapplication

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import kotlinx.android.synthetic.main.activity_exercise_selection.*
import android.content.Intent
import android.view.View
import android.widget.Button
import android.widget.Toast
import androidx.constraintlayout.widget.ConstraintLayout




class ExerciseSelectionActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_exercise_selection)

        ReadingTestExerciseButton.setOnClickListener {
            if (listReadingTest.visibility == View.VISIBLE) listReadingTest.visibility = View.GONE else listReadingTest.visibility = View.VISIBLE
        }

        SentencesExerciseButton.setOnClickListener {

        }

        FlashcardsExerciseButton.setOnClickListener {

        }

        buttonDemoExample.setOnClickListener {
            val intent = Intent(this, ReadingWithTestActivity::class.java)
            startActivity(intent)
        }
        ExerciseSearchButton.setOnClickListener {
            val intent = Intent(this, ExerciseSearchActivity::class.java)
            startActivity(intent)
        }

        //Creating buttons for Task Selection List
        var buttonAmount = 15
        var buttonNames = Array(buttonAmount) { i -> "AutoGeneratedButton no. $i" }

        for (buttonName in buttonNames){
            val newButton = Button(this)
            newButton.layoutParams = ConstraintLayout.LayoutParams(ConstraintLayout.LayoutParams.MATCH_PARENT, ConstraintLayout.LayoutParams.MATCH_PARENT)
            newButton.text = buttonName
            newButton.setOnClickListener {
                Toast.makeText(applicationContext, "Add demo Reading Test here.", Toast.LENGTH_SHORT).show()
            }

            linearLayoutTaskSelection.addView(newButton)
        }
    }

}
