package com.example.myapplication

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.Toast
import androidx.constraintlayout.widget.ConstraintLayout
import kotlinx.android.synthetic.main.activity_exercise_search.*
import kotlinx.android.synthetic.main.activity_exercise_selection.*

class ExerciseSearchActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_exercise_search)

        //Creating buttons representing results
        var buttonAmount = 15
        var buttonNames = Array(buttonAmount) { i -> "AutoGeneratedResult no. $i" }

        for (buttonName in buttonNames){
            val newButton = Button(this)
            newButton.layoutParams = ConstraintLayout.LayoutParams(ConstraintLayout.LayoutParams.MATCH_PARENT, ConstraintLayout.LayoutParams.MATCH_PARENT)
            newButton.text = buttonName
            newButton.setOnClickListener {
                Toast.makeText(applicationContext, "Add demo Reading Test here.", Toast.LENGTH_SHORT).show()
            }

            linearLayoutExerciseSearch.addView(newButton)
        }
    }
}
