package com.example.myapplication

import android.content.Intent
import android.os.Bundle
import android.view.View
import android.widget.Button
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.constraintlayout.widget.ConstraintLayout
import kotlinx.android.synthetic.main.activity_exercise_selection.*


class ExerciseSelectionActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_exercise_selection)

        ReadingTestExcerciseButton.setOnClickListener {
            if (listReadingTest.visibility == View.VISIBLE) listReadingTest.visibility =
                View.GONE else listReadingTest.visibility = View.VISIBLE
        }

        SentencesExcerciseButton.setOnClickListener {
            val mainActivity = Intent(applicationContext, SentenceActivity::class.java)
            startActivity(mainActivity)
        }

        FlashcardsExcerciseButton.setOnClickListener {
            val mainActivity = Intent(applicationContext, FlashcardsActivity::class.java)
            startActivity(mainActivity)
        }

        buttonDemoExample.setOnClickListener {
            val intent = Intent(this, ReadingWithTestActivity::class.java)
            startActivity(intent)
        }

        //Creating buttons for Task Selection List
        var buttonAmount = 15
        var buttonNames = Array(buttonAmount) { i -> "AutoGeneratedButton no. $i" }

        for (buttonName in buttonNames) {
            val newButton = Button(this)
            newButton.layoutParams = ConstraintLayout.LayoutParams(
                ConstraintLayout.LayoutParams.MATCH_PARENT,
                ConstraintLayout.LayoutParams.MATCH_PARENT
            )
            newButton.text = buttonName
            newButton.setOnClickListener {
                Toast.makeText(
                    applicationContext,
                    "Add demo Reading Test here.",
                    Toast.LENGTH_SHORT
                ).show()
            }

            linearLayoutTaskSelection.addView(newButton)
        }
    }

}
